name: backend-ci-workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - starter/backend

env:
  PYTHON-VERSION: "3.10"
  
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{env.PYTHON-VERSION}}
          cache: 'pip'
      - name: Install pipenv
        run: pip install pipenv
      - name: Install dependencies
        run: |
          cd starter/backend
          pipenv install        
      - name: Run lint
        run: |
          cd starter/backend
          pipenv run lint
        #continue-on-error: true        

  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{env.PYTHON-VERSION}}
      - name: Install dependencies
        run: |
          cd starter/backend
          pipenv install
      - name: Run tests 
        run: |
          cd starter/backend
          pipenv run test
        #continue-on-error: true
        
  dev-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Display message
        run: echo "These are the Development notes"

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: ${{env.PYTHON-VERSION}}
      - name: Install dependencies
        run: |
          cd starter/backend
          pipenv install
      - name: Run tests 
        run: |
          cd starter/backend
          pipenv run test
        #continue-on-error: true          
      - name: Build Docker Image
        run: |
          cd starter/backend
          docker build --tag ap-backend:latest .