name: Backend Continuous Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'starter/backend/**'

env:
  PYTHON-VERSION: "3.10"
  
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{env.PYTHON-VERSION}}
      - name: Install pipenv
        run: pip install pipenv
      - name: Install dependencies
        run: |
          cd starter/backend
          pipenv install --dev
#          pipenv run lint
      - name: Run lint
        run: |
          cd starter/backend
          pipenv run lint
        #continue-on-error: true        

  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{env.PYTHON-VERSION}}
      - name: Install pipenv
        run: pip install pipenv
      - name: Install dependencies
        run: |
          cd starter/backend
          pipenv install
#          pipenv run test
      - name: Run tests 
        run: |
          cd starter/backend
          pipenv run test
        #continue-on-error: true

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: ${{env.PYTHON-VERSION}}
      - name: Install pipenv
        run: pip install pipenv
      - name: Install dependencies
        run: |
          cd starter/backend
          pipenv install
      - name: Run tests 
        run: |
          cd starter/backend
          pipenv run test
        #continue-on-error: true          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{secrets.AWS_SESSION_TOKEN}}
          aws-region: us-east-1      
      - name: Build and push Docker Image to AWS ECR
        run: |
          cd starter/backend
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 416216733404.dkr.ecr.us-east-1.amazonaws.com
          docker build --tag=ap-udacity-mp-backend:latest .
          docker tag ap-udacity-mp-backend:latest 416216733404.dkr.ecr.us-east-1.amazonaws.com/ap-udacity-mp-backend:latest
          docker push 416216733404.dkr.ecr.us-east-1.amazonaws.com/ap-udacity-mp-backend:latest        

  Deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{secrets.AWS_SESSION_TOKEN}}
          aws-region: us-east-1          
      - name: Deploy to K8 cluster
        run: |
          cd starter/backend/k8s
          aws eks update-kubeconfig --region us-east-1 --name ap-udacity-mp-cluster
          kustomize edit set image backend=416216733404.dkr.ecr.us-east-1.amazonaws.com/ap-udacity-mp-backend:latest
          kustomize build | kubectl apply -f -          