name: frontend-ci-workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  NODE-VERSION: 18
  
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE-VERSION}}
      - name: Install dependencies
        run: |
          cd starter/frontend
          npm ci          
      - name: Run lint
        run: |
          cd starter/frontend
          npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE-VERSION}}
      - name: Install dependencies
        run: |
          cd starter/frontend
          npm ci
      - name: Run tests 
        run: |
          cd starter/frontend
          CI=true npm test --passWithNoTests
        
  dev-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Display message
        run: echo "These are the Development notes"

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE-VERSION}}
      - name: Install dependencies
        run: |
          cd starter/frontend
          npm ci
