name: frontend-ci-workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  NODE-VERSION: 18.14
  REACT_APP_MOVIE_API_URL: 'http://localhost:5000'
  
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE-VERSION}}
      - name: Install dependencies
        run: |
          cd starter/frontend
          npm ci          
      - name: Run lint
        run: |
          cd starter/frontend
          npm run lint --fix
        continue-on-error: true        

  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE-VERSION}}
      - name: Install dependencies
        run: |
          cd starter/frontend
          npm ci
      - name: Run tests 
        run: |
          cd starter/frontend
          npm test --passWithNoTests
        continue-on-error: true
        
  dev-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Display message
        run: echo "These are the Development notes"

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE-VERSION}}
      - name: Install dependencies
        run: |
          cd starter/frontend
          npm ci
      - name: Run tests 
        run: |
          cd starter/frontend
          npm test --passWithNoTests
        continue-on-error: true          
      - name: Build Docker Image
        run: docker build --build-arg=REACT_APP_MOVIE_API_URL=${{REACT_APP_MOVIE_API_URL}} --tag=ap-frontend:latest .